Error: change a whole bunch error messages' prefix (#1657)
* Error: change a whole bunch error messages' prefix

Long ago we started using 'bad ...' as the error messages, the "dns:"
prefix is used for panic's not in normal errors, remove are replace a
whole bunch of "dns:" with "bad ..."

Signed-off-by: Miek Gieben <miek@miek.nl>

* Error: change a whole bunch error messages' prefix

Long ago we started using 'bad ...' as the error messages, the "dns:"
prefix is used for panic's not in normal errors, remove are replace a
whole bunch of "dns:" with "bad ..."

Signed-off-by: Miek Gieben <miek@miek.nl>

* Use "bad" here too and use terminoloy from Msg struct

Extra instead of Ar count

Signed-off-by: Miek Gieben <miek@miek.nl>

---------

Signed-off-by: Miek Gieben <miek@miek.nl>