Error: change a whole bunch error messages' prefix
Long ago we started using 'bad ...' as the error messages, the "dns:"
prefix is used for panic's not in normal errors, remove are replace a
whole bunch of "dns:" with "bad ..."

Signed-off-by: Miek Gieben <miek@miek.nl>